displayName=Prometheus Skill Exporter
author=Cody Fraker
description=Exports all skilling data to a Prometheus endpoint for Grafana visualization
tags=stats,skills,prometheus,grafana,export
plugins=net.runelite.plugins.prometheusskillexporter.PrometheusSkillExporterPlugin

